= CECOBAN - Open Banking Platform

OpenID Connect Issuer

    https://3scale-admin:74364830-2eaf-47c7-8d40-8ccc78f1cb03@sso-sso.apps.cecoban-0142.openshiftworkshop.com/auth/realms/openbanking


Testing using Postman: 

    Authorization Code
    https://www.getpostman.com/oauth2/callback
    https://sso-sso.apps.cecoban-0142.openshiftworkshop.com/auth/realms/openbanking/protocol/openid-connect/auth
    https://sso-sso.apps.cecoban-0142.openshiftworkshop.com/auth/realms/openbanking/protocol/openid-connect/token
    0277d506
    2f8de72cbb2284f1064af175d793c4b8


RHSSO Credentials:
* user: adminadmin
* passwd 328bb342d5814a2cbb3ced07a29967e3

Portal Credentials: 
* user: admin@example.com
* passwd: #Cecoban!

RHSSO User auth: 
* user: cecoban
* passwd: #Cecoban!

Kibana URL:
https://kibana.apps.cecoban-0142.openshiftworkshop.com

Login application Developer Portal
* user: ramalho
* passwd: #Cecoban!


URL Rewrite: 

    banks
    obp/v3.1.0/banks

3Scale OIDC 

    https://3scale-admin:74364830-2eaf-47c7-8d40-8ccc78f1cb03@sso-sso.apps.cecoban-0142.openshiftworkshop.com:443/auth/realms/openbanking
    https://sso-sso.apps.cecoban-0142.openshiftworkshop.com/auth/realms/openbanking
    https://sso-sso.apps.cecoban-0142.openshiftworkshop.com/auth/realms/openbanking/.well-known/openid-configuration

Open License in Developer Portal

https://www.openbanking.org.uk/open-licence/

Developer Portal Access Code
* cecoban

Developer Portal SSO Integration

    Client ID: 38b201d8
    Client Secret: b9c2ecfedbf8be291302385c5eee0b1d
    Redirect URL: https://3scale.apps.cecoban-0142.openshiftworkshop.com/docs

== Useful references

Glossary: https://www.openbanking.org.uk/about-us/glossary/

Open Data API Specifications: https://openbanking.atlassian.net/wiki/spaces/DZ/pages/16320694/Open+Data+API+Specifications
Open Data API Sample Data: https://openbanking.atlassian.net/wiki/spaces/DZ/pages/519143683/Open+Data+API+Dashboard

ATM Spec: https://openbanking.atlassian.net/wiki/spaces/DZ/pages/230163079/ATM+API+Specification+v2.2.0#ATMAPISpecification_v2.2.0-Swagger

ATM Sample

https://openbanking.santander.co.uk/sanuk/external/open-banking/v2.2/atms



== Roteiro V1.

Insert Rate Limit.

Slide Deck: https://docs.google.com/presentation/d/1lACiIeu9fgtrJ6K69ApC6AhowVtIzrPwP8PQZW90jHM/edit#slide=id.g31db18e50f_0_0
3Scale: https://3scale-admin.apps.cecoban-0142.openshiftworkshop.com
Single Sign On: https://sso-sso.apps.cecoban-0142.openshiftworkshop.com
Developer Portal: https://3scale.apps.cecoban-0142.openshiftworkshop.com
Locations app: http://www-openbankingclient.apps.cecoban-0142.openshiftworkshop.com

Autenticar pelo 3Scale!
ramalho
#Cecoban!

Openshift: https://master.cecoban-0142.openshiftworkshop.com/console/project/openbankingclient/overview

